<?php

namespace App\Presenters;

use Nette;
use Nette\Application\UI\Form;

/**
 * Base presenter for all application presenters.
 */
abstract class BasePresenter extends Nette\Application\UI\Presenter
{
    protected function startup()
    {
        parent::startup(); // TODO: Change the autogenerated stub
        if (!$this->getUser()->isLoggedIn())
        {
            if ($this->getHttpRequest()->getUrl()->path != "/socialnetwork-assignment/www/sign/in")
            {
                if ($this->getHttpRequest()->getUrl()->path != "/socialnetwork-assignment/www/sign/up")
                    $this->redirect("Sign:in");
            }
        }
    }

    protected function createComponentSearch()
    {
        $form = new Form;
        $form->addText('content', 'Vyhledávání')
            ->setRequired('Zadejte prosím text');
        $form->addSubmit('submit','Vyhledat');
        $form->onSuccess[] = [$this, 'SearchSuccess'];
        return $form;
    }

    public function SearchSuccess($form, $values)
    {
        $this->redirect('Search:', array('search' => $values->content));
    }
}
